### PR TITLE
Added payout support.

### PR DESCRIPTION
**Pull request by SwiTool**
I can't make any more tests because I am "Not allowed"...

### CODE REVIEW

**Comment by rikterbeek** [comment]
hi @SwiTool,

Thanks for the PR this looks very good. Would you able to add more test cases ? You can contact support@adyen.com to ask for the permissions. For the test environment we can just enable it.

Regards,
Rik
Adyen


Regards,

**Comment by SwiTool** [comment]
Hey @rikterbeek could you check now please ?

**Comment by SwiTool** [comment]
Hello @rikterbeek please review it

**Comment by rikterbeek** [comment]
Hi @SwiTooll,

Thank you very much for contributing this code we highly appreciate it. Could you reply on the mail that you already send to us and provide us your address details. We will send you a gift to appreciate making a contribution to our code.

Regards,
Rik
Adyen

**Pull request merged**
