### PR TITLE
Feature/gh refund with data

### PR DESCRIPTION
**Pull request by sufcboy**
**Description**

**Tested scenarios**

**Fixed issue**:

### CODE REVIEW

**Comment by cyattilakiss** [comment]
Hi @sufcboy ,

Thank you for the PR, we are going to review it and then merge it.

Best,
Attila
Adyen

**Comment by rikterbeek** [comment]
HI @sufcboy,

Many thanks for the PR! It looks good and we can merge it. It would be great to have some test cases alongside this are you able to add this ?

Regards,
Rik
Adyen

**Comment by sufcboy** [comment]
I've added a single success path test. This corresponds to the fund test.

**Comment by rikterbeek** [comment]
HI @sufcboy,

Thanks! I will merge this.

Regards,
Rik
Adyen

**Pull request merged**
