### PR TITLE
#57 Fix directoryLookup call

### PR DESCRIPTION
**Pull request by rikterbeek**
**Description**

Fix Directory Lookup call

**Tested scenarios**

Executed all test successful
**Fixed issue**:  
#57

### CODE REVIEW

**Comment by ogarbe** [comment]
please deploy a 1.4.2 quickly as 1.4.1 is broken....

**Comment by rikterbeek** [comment]
Hi @ogarbe,

Can you check if current release works because it could be a hickup in our test environment.

Regards,
Rik
Adyen

**Comment by cbulgariu** [comment]
Hello Rik

the change you proposed works on test environment.

Regards,
Claudiu

**Comment by ogarbe** [comment]
we confirm (@cbulgariu  works in my team).

**Pull request merged**
