### PR TITLE
[PW-8298] Added ach to ManualCapture.php to allow for manual Invoicing

### PR DESCRIPTION
**Pull request by carlosperales95**
**Description**
In order for ACH manual captures to work, I added the variant to the Manual capture list.

**Tested scenarios**
1. Order without ACH present in the list:
With current list, ACH payments will go to Processing automatically when the payment is fully authorised, even with `Capture Delay = Manual` setting in Magento.

2. Order with ACH present in the list:
With the new list, if capture is set to manual, the order will stay on Pending status until the CAPTURE Notification is processed, just as expected with manual capture flow.

### CODE REVIEW

**Comment by carlosperales95** [comment]
PW was changed to ITT type, new ID is [ITT-400]

**Comment by carlosperales95** [comment]
It's been a month and still reviews are required. Will this ever be merged?

**Comment by jillingk** [comment]
@peterojo @candemiralp is this something you guys still need for magento? If so can you approve please.

**Comment by carlosperales95** [comment]
In Magento this list has been moved to the plugin code, so it's not needed within the library (already updated that list). However it might be still useful for merchants that build their own integration using this library.

**Review by AlexandrosMor — APPROVED** [review]

**Pull request merged**
